### ISSUE TITLE
Error: Please check your internet connection

### ISSUE THREAD

**Issue by forteller** [delight-im/Faceless#15]
I'm online via wifi, but still when I open the app and when I try to post something I get this message. Latest version via GitHub.

**Comment by mwaclawek** [comment]
Thanks for reporting this issue!

It was our fault, of course, sorry!

The APKs that were available didn't work anymore because the old server is gone. So, unfortunately, you have to build the application yourself in order to see a live demo.

The obsolete links and resources have thus been removed from the repository: https://github.com/delight-im/Faceless/commit/d4ed47440a8b368bfe63ffe03b20b19ccc533bd9
